### ISSUE TITLE
Milestone and to-dos of project

### ISSUE THREAD

**Issue by mooner1022** [mooner1022/StarLight#17]
- [ ] Add user-created project template
- [ ] Add implementations of `Legacy Api` and `Api2`
- [ ] Load external scripts on compile
- [ ] Finish incomplete plugin event listener load code
- [ ] Add event broadcaster for plugins
